[build]
  command = "npm run build"
  publish = "build"

## Ensure Vite module endpoints are NOT rewritten by SPA rule
[[redirects]]
  from = "/@vite/*"
  to = "/@vite/:splat"
  status = 200

[[redirects]]
  from = "/@react-refresh/*"
  to = "/@react-refresh/:splat"
  status = 200

[[redirects]]
  from = "/src/*"
  to = "/src/:splat"
  status = 200

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://website-builder-3hm1.onrender.com/api/:splat"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "20"

# SPA routing: send app routes to index.html so react-router works on refresh/deeplinks
# Keep this AFTER module/asset pass-through rules above
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 8888        # Netlify dev server port
  targetPort = 3000  # Vite dev server port

