[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# SPA routing: send all routes to index.html so react-router works on refresh/deeplinks
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 8888        # Netlify dev server port
  targetPort = 3000  # Vite dev server port

